import { ISliderProperties } from '../interfaces';

/** Default properties values */
export const DEFAULT_PROPERTIES_VALUES: ISliderProperties = {
  animation: true,
  width: 18,
  circleShape: 'full',
  disabled: false,
  editableTooltip: true,
  endAngle: '+360',
  handleSize: '+0',
  handleShape: 'round',
  keyboardAction: true,
  lineCap: 'butt',
  max: 100,
  min: 0,
  mouseScrollAction: false,
  radius: 85,
  readOnly: false,
  showTooltip: true,
  sliderType: 'default',
  startAngle: 0,
  startValue: null,
  step: 1,
  value: null,
  svgMode: false,
  borderWidth: 1,
  borderColor: null,
  pathColor: null,
  rangeColor: null,
  tooltipColor: null,
}
