FROM node:alpine as builder
WORKDIR /storybook-wrapper
COPY package.json package-lock.json /storybook-wrapper/
RUN npm ci
COPY . /storybook-wrapper
RUN npm run slider:build-storybook

FROM nginx:alpine
COPY libs/ng-round-slider/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /storybook-wrapper/dist/storybook/ng-round-slider /usr/share/nginx/html