name: Library Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]
  push:
      branches: [ "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Get dependencies
      run: npm ci
    - name: Run linter
      run: npm run slider:lint

  build-storybook:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Get dependencies
      run: npm ci
    - name: Run build storybook
      run: npm run slider:build-storybook

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Get dependencies
      run: npm ci
    - name: Run build
      run: npm run slider:build